using System;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using SwiftlyS2.Shared;
using SwiftlyS2.Shared.Commands;
using SwiftlyS2.Shared.Players;
using Microsoft.Extensions.Logging;
using Iridium.Config;

namespace Iridium.Admin;

public class ServerCommands
{
    private readonly ISwiftlyCore _core;
    private readonly Iridium _plugin;
    private readonly SmartRconManager _smartRcon;

    // We track the active executor and buffer their output
    private IPlayer? _activeRconExecutor;
    private StringBuilder _rconOutputBuffer = new();
    
    // Pre-compiled regex for stripping ANSI color codes (highly optimized)
    private static readonly Regex AnsiRegex = new Regex(@"\x1B\[[0-9;]*[a-zA-Z]", RegexOptions.Compiled);

    public ServerCommands(ISwiftlyCore core, Iridium plugin, SmartRconManager smartRcon)
    {
        _core = core;
        _plugin = plugin;
        _smartRcon = smartRcon;

        _core.Event.OnConsoleOutput += (@event) =>
        {
            if (_activeRconExecutor != null)
            {
                // Strip the raw ANSI color codes generated by the server/logger
                string cleanMsg = AnsiRegex.Replace(@event.Message ?? "", "");

                // Filter out SwiftlyS2's own logger prefixes to prevent spam loops
                if (cleanMsg.Contains("Iridium |") || cleanMsg.Contains("SwiftlyS2 |") || cleanMsg.Contains("[Iridium RCON]"))
                    return;

                string trimmedMsg = cleanMsg.TrimEnd();
                if (string.IsNullOrWhiteSpace(trimmedMsg)) return;

                // Store in buffer for the chat output
                _rconOutputBuffer.AppendLine(trimmedMsg);
                
                // Echo cleanly to the specific admin's client console in plain text
                string consoleOutput = trimmedMsg + "\n";
                _activeRconExecutor.SendConsole(consoleOutput);
            }
        };
    }

    [Command("rcon")]
    public async Task OnRconCommandAsync(ICommandContext context)
    {
        var admin = context.Sender;
        
        if (admin != null)
        {
            var rconPerm = _plugin.Config.Server.RconPermission;
            if (!string.IsNullOrEmpty(rconPerm) && !_core.Permission.PlayerHasPermission(admin.SteamID, rconPerm))
            {
                admin.SendChat($" \x02[Iridium]\x01 You do not have permission to execute RCON commands.");
                return;
            }
        }

        if (context.Args.Length == 0)
        {
            var msg = " \x02[Iridium]\x01 Usage: !rcon <command>";
            if (admin != null) admin.SendChat(msg);
            else _core.Logger.LogInformation(msg);
            return;
        }

        string baseCommand = context.Args[0].ToLowerInvariant();
        string commandPayload = string.Join(' ', context.Args).Trim();

        // 1. Safety verification
        if (_plugin.Config.Server.BlockedRconCommands.Contains(baseCommand, StringComparer.OrdinalIgnoreCase))
        {
            SendBeautifulError(admin, "The command '", baseCommand, "' is blocked for safety reasons.");
            return;
        }

        // 2. Smart RCON Validation & Suggestions
        if (!_smartRcon.IsKnownCommand(baseCommand))
        {
            var suggestions = _smartRcon.GetSuggestions(baseCommand, 3);
            if (suggestions.Count > 0)
            {
                SendBeautifulError(admin, "Unknown command '", baseCommand, "'.");
                if (admin != null)
                {
                    admin.SendChat($" \x01• Did you mean: \x04{string.Join("\x01, \x04", suggestions)}\x01?");
                }
                return;
            }
        }

        // 3. Execution & Output Capture
        _rconOutputBuffer.Clear();
        if (admin != null) 
        {
            _activeRconExecutor = admin;
            // Inject 50 blank lines to visually "clear" the player's client console of spam
            string visualClear = new string('\n', 50);
            admin.SendConsole($"{visualClear}\n--- [Iridium RCON] Executing: {commandPayload} ---\n");
        }
        
        // Execute the command in the engine
        _core.Engine.ExecuteCommand(commandPayload);
        
        string executorName = admin?.Controller?.PlayerName ?? "CONSOLE";

        // Asynchronously wait 100ms, then schedule the chat output back onto the MAIN thread.
        Task.Run(async () => 
        {
            await Task.Delay(100);
            
            _core.Scheduler.NextTick(() => 
            {
                string capturedOutput = _rconOutputBuffer.ToString().Trim();
                _activeRconExecutor = null;

                // 4. Logging and Confirmation
                _core.Logger.LogInformation("[Iridium RCON] {Admin} executed: {Command}", executorName, commandPayload);

                if (admin != null)
                {
                    admin.SendChat($" \x02[Iridium]\x01 RCON Execution Summary:");
                    admin.SendChat($" "); 
                    admin.SendChat($" \x01• Command: \x04{commandPayload}");
                    
                    if (string.IsNullOrWhiteSpace(capturedOutput))
                    {
                        admin.SendChat($" \x01• Status: \x04Executed successfully (no output)");
                    }
                    else
                    {
                        // If it's short (like reading a ConVar value), print it beautifully in chat!
                        var lines = capturedOutput.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries);
                        if (lines.Length <= 2)
                        {
                            string inlineOutput = string.Join(" | ", lines).Replace("\r", "");
                            
                            // Highlight true (green) and false (light red) automatically
                            // Fix C# hex string literal bug (\x0Ff parses as \x0FFA) by concatenating
                            inlineOutput = Regex.Replace(inlineOutput, @"\btrue\b", "\x04true\x01\x04", RegexOptions.IgnoreCase);
                            inlineOutput = Regex.Replace(inlineOutput, @"\bfalse\b", "\x0F" + "false\x01\x04", RegexOptions.IgnoreCase);

                            admin.SendChat($" \x01• Output: \x04{inlineOutput}");
                        }
                        else
                        {
                            // Too long for chat, direct them to console
                            admin.SendChat($" \x01• Output: \x04(Printed to console, too long for chat)");
                        }
                    }
                }
            });
        });
    }

    private void SendBeautifulError(IPlayer? admin, string baseText, string highlightText, string suffixText = "")
    {
        if (admin != null)
        {
            admin.SendChat($" \x02[Iridium]\x01 Error:");
            admin.SendChat($" "); 
            admin.SendChat($" \x01• {baseText}\x10{highlightText}\x01{suffixText}");
        }
        else
        {
            _core.Logger.LogWarning($"[Iridium RCON] {baseText}{highlightText}{suffixText}");
        }
    }
}
