name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"
        
    - name: Restore dependencies
      run: dotnet restore Iridium.csproj
      
    - name: Build and Package
      run: |
        dotnet publish Iridium.csproj -c Release -o output/Iridium
        
        # Create a zip containing the Iridium folder for easy installation
        cd output
        zip -r ../Iridium-latest.zip Iridium/
        cd ..
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Iridium-latest
        path: Iridium-latest.zip
